### ISSUE TITLE
[fix] 게시글과 좋아요 간의 연관관계를 추가하고  updateBoard 메서드의 이름을 변경한다.  그리고 BoardDto 클래스에 불필요한 @Getter을 삭제한다

### ISSUE THREAD

**Issue by Chaseungjun** [puppypawpaw/Pawpaw_project_BE#17]
## Description(설명)
- 게시글과 좋아요 간에 추가하지 못한 OneToMany 연관관계를 추가한다.
- BoardDto 클래스에 불필요한 @Getter을 삭제한다.
- 게시글의 제목과 내용을 수정하는 pdateBoard메서드의 이름을 updateTitleAndContent 로 바꾸고 updateTitle, updateContent는 삭제한다.

## Tasks(New feature)
- [x] 게시글과 좋아요 간의 연관관계 추가
- [x] Board의 메서드 이름변경 및 기존 메서드 삭제
- [x] BoardDto 클래스 @Getter 어노태이션 삭제
