### ISSUE TITLE
[feat] Paw zone api 구현 

### ISSUE THREAD

**Issue by alpapago** [puppypawpaw/Pawpaw_project_BE#19]
## Description(설명)
paw zone에서 장소를 검색하고, 방문한 장소 대한 리뷰와 댓글, 좋아요를 남길 수 있는 기능을 만든다.

## To-do

로그인 한 유저의 장소 리뷰

- [ ] 장소에 대해서 6개 항목에 대한 평가 crud 
- [ ] 장소 text 포스팅 리뷰 crud 구현
- [ ] 장소 리뷰에 댓글 crud 구현
- [ ] 장소 즐겨찾기 api 구현

장소 검색
- [ ] 핀 누르면, 장소 위,경도 불러오기

**Comment by alpapago** [comment]
cancel
