### ISSUE TITLE
[feat] 게시판의 이미지 업로드 기능과 썸네일 기능을 구현한다.

### ISSUE THREAD

**Issue by Chaseungjun** [puppypawpaw/Pawpaw_project_BE#20]
## Description(설명)
게시글을 작성할 때, 이미지를 업로드하는 기능과 썸네일 기능을 구현한다.

## Tasks(New feature)
- [ ] 이미지 업로드 기능
- [ ] 썸네일 기능
- [ ] 테스트 코드 작성
- [ ] 예외처리를 위한 예외코드와 핸들러코드 작성
