### ISSUE TITLE
[fix] 게시글 좋아요 추가, 제거 기능을 구현한 하나의 메서드를 추가 메서드, 제거 메서드로 분리, 에러코드와 핸들러 추가, 테스트 코드 작성

### ISSUE THREAD

**Issue by Chaseungjun** [puppypawpaw/Pawpaw_project_BE#22]
## Description(설명)
게시글 좋아요 추가, 제거 기능을 구현한 하나의 메서드를 추가 메서드, 제거 메서드로 분리한다.
에러코드와 핸들러 추가하고 이전에 작성하지 못했던 테스트 코드를 작성한다.

## Tasks(New feature)
- [ ] 좋아요 추가, 제거 메서드 분리
- [ ] 에러코드, 핸들러 추가
- [ ] 테스트 코드 작성
