### ISSUE TITLE
[feat] 게시글 예외코드 및 예외처리 코드 추가, BoardController에 swagger 코드 추가, JpaRepository에 직접 의존하는 코드를 수정

### ISSUE THREAD

**Issue by Chaseungjun** [puppypawpaw/Pawpaw_project_BE#29]
## Description(설명)
게시글 예외코드 및 예외처리 코드 추가하고, 게시판에 관련된 전반적인 코드를 수정한다.

## Tasks(New feature)
- [x] 게시글 예외코드 및 예외처리 코드 추가
- [x] BoardController에 swagger 코드 추가
- [x] JpaRepository에 직접 의존하는 코드를 수정
- [x] 불필요한 코드 수정 및 어노테이션 제거
