### ISSUE TITLE
[fix] 좋아요 예외코드 및 예외처리 코드 추가, 좋아요 추가,삭제 기능을 분리, BoardLikeController에 swagger 코드 추가, JpaRepository에 직접 의존하는 코드를 수정 

### ISSUE THREAD

**Issue by Chaseungjun** [puppypawpaw/Pawpaw_project_BE#34]
## Description(설명)
좋아요 기능의 전반전인 코드를 수정한다.

## Tasks(New feature)
- [x] 좋아요 예외코드 및 예외처리 코드 추가
- [x] 좋아요 추가,삭제 기능을 분리
- [x] BoardLikeController에 swagger 코드 추가
- [x] JpaRepository에 직접 의존하는 코드를 수정
