### ISSUE TITLE
[fix] 이미지 업로드 및 조회 코드, 북마크 등록과 조회 코드 수정, nullException 처리

### ISSUE THREAD

**Issue by Chaseungjun** [puppypawpaw/Pawpaw_project_BE#92]
## Description(설명)
게시글에 이미지 업로드, 수정, 조회에 관한 전반적인 코드를 수정했다. 

## Tasks
- [x] 이미지 업로드 및 조회 수정
- [x] 북마크 등록과 조회 코드 수정
- [x] nullException 처리
- [x] 댓글의 등록날짜와 수정날짜 추가
